apiVersion: v1
kind: ConfigMap
metadata:
  name: search-replace-fn-config
  # TODO:(pmarupaka) remove annotations when e2e tests switch to kpt v1 binary
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/search-replace:unstable
data:
  by-path: metadata.name
  by-value: the-deployment
  put-value: my-deployment
