apiVersion: fn.kpt.dev/v1alpha1
kind: ConfigMapGenerator
metadata: # kpt-merge: example/mariadb
  name: mariadb
  namespace: example
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ConfigMapGenerator|example|mariadb'
spec:
  source:
  - format: IniFile # optional
    localFileRef: mycnf-ini-file
    asConfigMap: true
