apiVersion: v1
kind: Deployment
metadata:
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/StatefulSet/wordpress-mysql
  labels:
    app: wordpress
  name: wordpress
  namespace: default
---
apiVersion: v1
kind: StatefulSet
metadata:
  labels:
    app: wordpress
  name: wordpress-mysql
  namespace: default
---
apiVersion: v1
kind: Deployment
metadata:
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/StatefulSet/outside-resource
  labels:
    app: bar
  name: bar
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.kubernetes.io/depends-on: rbac.authorization.k8s.io/ClusterRole/secret-reader
  name: read-secrets-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
