apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewers
  namespace: shipping-staging
roleRef:
  name: view
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: 'system:serviceaccounts:audit'
  kind: Group
  apiGroup: rbac.authorization.k8s.io
