apiVersion: kpt.dev/v1
kind: FunctionResultList
metadata:
  name: fnresults
exitCode: 0
items:
  - image: gcr.io/kpt-fn/set-image:unstable
    exitCode: 0
    results:
      - message: updated image from nginx:1.20.2 to bitnami/nginx@sha256:e1d6f00f191515945233f562777fc9ab3b7637ea75169b3dd628d46c9b24400f
        severity: info
        resourceRef:
          apiVersion: v1
          kind: Pod
          name: app1
        file:
          path: resources.yaml
      - message: updated image from nginx:1.20.2 to bitnami/nginx@sha256:e1d6f00f191515945233f562777fc9ab3b7637ea75169b3dd628d46c9b24400f
        severity: info
        resourceRef:
          apiVersion: v1
          kind: Pod
          name: app2
        file:
          path: resources.yaml
          index: 1
      - message: 'summary: updated a total of 2 image(s)'
        severity: info