apiVersion: kpt.dev/v1beta1
kind: StarlarkFunction
metadata:
  name: my-star-fn
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/starlark:unstable
source:
  path: /starlark/helloworld.star
keyValues:
  foo: baz
