apiVersion: fn.kpt.dev/v1alpha1
kind: EnsureNameSubstring
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/local-config: "true"
additionalNameFields:
  - kind: MyResource
    group: dev.example.com
    path: spec/name
    version: v1
editMode: prepend
substring: prod-
