apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: frontend-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-app
  namespace: example
  labels:
    test: abstract-base-app
    app.kubernetes.io/name: frontend
spec:
  selector:
    matchLabels:
      test: abstract-base-app
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        test: abstract-base-app
        app.kubernetes.io/name: frontend
