apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: blog
          image: ghost:2.6-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: http://my-blog.com