apiVersion: v1
kind: Service
metadata:
  name: the-service
  namespace: example
---
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: the-crd
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: crd-svc
          namespace: example
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: the-api-service
spec:
  service:
    name: api-svc
    namespace: example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb1
subjects:
  - kind: ServiceAccount
    name: default
    namespace: example
