apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: test-simple
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    another-annotation: will-be-inherited
    one-more-annotation: folders-will-inherit-too
spec:
  parentRef:
    kind: Organization
    external: test-organization
  config:
    - Dev
    - Prod
