apiVersion: cft.dev/v1alpha2
kind: ResourceHierarchy
metadata:
  name: test-simple
  annotations:
    config.kubernetes.io/local-config: 'true'
    cnrm.cloud.google.com/deletion-policy: abandon
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/generate-folders:unstable
spec:
  parentRef:
    kind: Organization
    external: test-organization
  config:
    - Dev
    - Prod
    - Test
