apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: test-simple
  annotations:
spec:
  parentRef:
    kind: Organization
    external: test-organization
  config:
    - Dev
    - Prod