apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: test-simple
  annotations:
    config.kubernetes.io/path: config.yaml
    config.kubernetes.io/index: 3
spec:
  parentRef:
    kind: Organization
    external: test-organization
  config:
    - Dev
    - Prod