apiVersion: cft.dev/v1alpha2
kind: ResourceHierarchy
metadata:
  name: test-simple
spec:
  parentRef:
    external: test-organization
  subtrees:
    deep:
      - subtree:
        - nested:
          - very
  config:
    - prod:
        $subtree: deep
    - dev:
        $subtree: deep