apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: test-simple
  namespace: foo
spec:
  parentRef:
    kind: Organization
    external: test-organization
  config:
    - Dev:
      - Team_2
    - Prod:
      - Team_2
    - Foo:
      - bar
