apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-functions/istioctl-analyze
    config.kubernetes.io/local-config: 'true'
data:
  '--use-kube': 'false'
