apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: inject-sidecar-to-depl
  annotations:
    config.kubernetes.io/local-config: "true"
source: |
  def ensure_inject_sidecar_to_depl(r):
    if r["apiVersion"] == "apps/v1" and r["kind"] == "Deployment":
      containers = r["spec"]["template"]["spec"]["containers"]
      for container in containers:
        if container["name"] == "logging-agent":
          return
      sidecar = {
        "name": "logging-agent",
        "image": "k8s.gcr.io/fluentd-gcp:1.30",
      }
      containers.append(sidecar)

  for resource in ctx.resource_list["items"]:
    ensure_inject_sidecar_to_depl(resource)
