apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: server
    image: nginx:1.20.2
  - name: store
    image: postgres:14.1
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: store
    image: redis:6.2.6
  - name: server
    image: nginx:1.20.2
