apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-setters-fn-config
  # TODO:(pmarupaka) remove annotations when e2e tests switch to kpt v1 binary
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/apply-setters:v0.1
data:
  name: my-new-map
  env: |
    - prod
    - stage
