apiVersion: fn.kpt.dev/v1alpha1
kind: SetLabelConfig
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/set-label:v0.1
    config.kubernetes.io/local-config: "true"
labels:
  color: orange
  fruit: apple
fieldSpecs:
- kind: MyResource
  group: dev.example.com
  version: v1
  create: true
  path: spec/selector/labels
