apiVersion: v1
kind: ConfigMap
metadata:
  name: my-decrypt-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn-contrib/sops:unstable
        envs:
        - SOPS_IMPORT_PGP
    config.kubernetes.io/local-config: "true"
data:
  cmd: 'decrypt'
  cmd-json-path-filter: '$[?(@.metadata.name=="toDecrypt")]'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-encrypt-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn-contrib/sops:unstable
        envs:
        - SOPS_IMPORT_PGP
    config.kubernetes.io/local-config: "true"
data:
  cmd: 'encrypt'
  cmd-json-path-filter: '$[?(@.metadata.name=="toEncrypt")]'
  pgp: 'FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4'
  unencrypted-regex: '^(kind|apiVersion|group|metadata)$'

