generators:
  - |-
    apiVersion: fn.kpt.dev/v1alpha1
    kind: RenderHelmChart
    metadata:
      name: demo
      annotations:
        config.kubernetes.io/function: |
          container:
            network: true
            image: gcr.io/kpt-fn/render-helm-chart:unstable
    helmCharts:
    - chartArgs:
        name: ocp-pipeline
        version: 0.1.16
        repo: https://bcgov.github.io/helm-charts
      templateOptions:
        namespace: mynamespace
        releaseName: moria
        values:
          valuesFiles:
            - https://raw.githubusercontent.com/natasha41575/kpt-functions-catalog/a9c9cd765a05f7a7fb6923dbde4651b62c9c229c/examples/render-helm-chart-kustomize-values-files/file1.yaml
            - https://raw.githubusercontent.com/natasha41575/kpt-functions-catalog/a9c9cd765a05f7a7fb6923dbde4651b62c9c229c/examples/render-helm-chart-kustomize-values-files/file2.yaml
