apiVersion: v1
kind: ConfigMap
metadata:
  name: my-encrypt-config
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  cmd: encrypt
  cmd-json-path-filter: '$[?(@.metadata.name=="toEncrypt")]'
  age: age1yt3tfqlfrwdwx0z0ynwplcr6qxcxfaqycuprpmy89nr83ltx74tqdpszlw
  unencrypted-regex: ^(kind|apiVersion|group|metadata)$
