apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.16.1"
          ports:
            - protocol: TCP
              containerPort: 80
---
apiVersion: v1
kind: MyKind
metadata:
  name: foo
environments:
  - dev
  - stage
