apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/search-replace:unstable
data:
  by-path: metadata.name
  by-value: the-deployment
  put-value: my-deployment
