apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-namespace-to-prod
source: |
  # set the namespace on all resources
  for resource in ctx.resource_list["items"]:
    # mutate the resource
    resource["metadata"]["namespace"] = "prod"
