apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-namespace-to-prod
source: |
  # set the namespace on all resources except Kptfile and StarlarkRun kind.
  for resource in ctx.resource_list["items"]:
    # mutate the resource
    if resource.get("kind") not in ["StarlarkRun", "Kptfile"]:
      resource["metadata"]["namespace"] = "prod"
