#!/bin/bash

cd functions/go;
echo "Generating docs..."
make generate;
diff=`git diff`

if [[ $diff != "" ]];
then 
        echo "found unstaged changes, verify generated docs and add them before commit"
        exit 1
else 
        exit 0
fi
