apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    foo: bar
    env: dev
  name: my-nginx
  namespace: my-space
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.14.2
          name: nginx
          ports:
            - containerPort: 80
