# call `kpt fn run` on a directory containing this file, mounting the kustomization directory at /source
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-functions/kustomize-build
    config.kubernetes.io/local-config: "true"
data:
  path: /source
  "--reorder": none
