apiVersion: v1
data:
  some-key: some-value
kind: ConfigMap
metadata:
  name: the-map
  namespace: the-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: the-pod
  namespace: the-namespace
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - env
      env:
        - name: SOME_KEY
          valueFrom:
            configMapKeyRef:
              key: some-key
              name: the-map
      image: k8s.gcr.io/busybox
      name: test-container
---
apiVersion: v1
kind: Service
metadata:
  name: the-service
  namespace: the-namespace
spec:
  ports:
    - name: etcd-server-ssl
      port: 2380
    - name: etcd-client-ssl
      port: 2379
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: the-namespace
