apiVersion: kpt.dev/v1alpha2
kind: FunctionResultList
metadata:
  name: fnresults
exitCode: 1
items:
  - image: gcr.io/kpt-fn-contrib/analyze-istio:unstable
    exitCode: 1
    results:
      - message: 'Istioctl analyze command results in error: function toString() { [native code] }'
        severity: error
      - message: 'Schema validation error: gateway must have at least one server'
        severity: error
        resourceRef:
          apiVersion: networking.istio.io/v1alpha3
          kind: Gateway
          name: httpbin-gateway
        file:
          path: istio-config.yaml
