apiVersion: v1
kind: ConfigMap
metadata:
  name: my-decrypt-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn-contrib/sops:unstable
        envs:
        - SOPS_IMPORT_AGE
    config.kubernetes.io/local-config: "true"
data:
  cmd: 'decrypt'
  cmd-json-path-filter: '$[?(@.metadata.name=="toDecrypt")]'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-encrypt-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn-contrib/sops:unstable
    config.kubernetes.io/local-config: "true"
data:
  cmd: 'encrypt'
  cmd-json-path-filter: '$[?(@.metadata.name=="toEncrypt")]'
  age: 'age1yt3tfqlfrwdwx0z0ynwplcr6qxcxfaqycuprpmy89nr83ltx74tqdpszlw'
  unencrypted-regex: '^(kind|apiVersion|group|metadata)$'

