secretGenerator:
  - name: my-secret
    envs:
      - credentials.env
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"

transformers:
  - |-
    apiVersion: fn.kpt.dev/v1alpha1
    kind: RenderHelmChart
    metadata:
      name: demo
      annotations:
        config.kubernetes.io/function: |
          container:
            network: true
            image: gcr.io/kpt-fn/render-helm-chart:unstable
    helmCharts:
    - chartArgs:
        name: mychart
        repo: https://raw.githubusercontent.com/kpt-helmfn-test-bot/private-helm-repo/main
        auth:
          kind: Secret
          name: my-secret
