secretGenerator:
  - name: my-secret
    literals:
      - username=_json_key
    files:
      - password
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"

transformers:
  - |-
    apiVersion: fn.kpt.dev/v1alpha1
    kind: RenderHelmChart
    metadata:
      name: demo
      annotations:
        config.kubernetes.io/function: |
          container:
            network: true
            image: gcr.io/kpt-fn/render-helm-chart:unstable
    helmCharts:
    - chartArgs:
        name: mychart
        repo: oci://us-west2-docker.pkg.dev/kustomize-326923/helloworld-chart
        registry: https://us-west2-docker.pkg.dev
        auth:
          kind: Secret
          name: my-secret
