apiVersion: v1
data:
  some-key: some-value
kind: ConfigMap
metadata:
  name: the-map
---
apiVersion: dev.example.com/v1
kind: MyResource
metadata:
  name: the-service
  namespace: the-namespace
spec:
  selector:
    labels:
      foo: bar
