# Function configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-functions/kubeval
        network:
          required: true
    config.kubernetes.io/local-config: 'true'
---
# Example Kubernetes configuration
# From https://github.com/instrumenta/kubeval.git/fixtures/invalid.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: bob
spec:
  replicas: asd" # Replace this value with an integer to pass validation.
  selector:
    app: nginx
  templates:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
