apiVersion: v1
kind: ConfigMap
metadata:
  name: my-decrypt-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  cmd: 'decrypt'
  cmd-json-path-filter: '$[?(@.metadata.name=="toDecrypt")]'
