apiVersion: kpt.dev/v1
kind: FunctionResultList
metadata:
  name: fnresults
exitCode: 0
items:
  - image: gcr.io/kpt-fn/remove-local-config-resources:unstable
    exitCode: 0
    results:
      - message: 'Number of resources pruned: 1'
      - message: 'Resource name: [sample-hierarchy]'
