apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-admin
  namespace: shipping-prod
roleRef:
  name: admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: sre@foo-corp.com
  kind: Group
  apiGroup: rbac.authorization.k8s.io
