apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    name: please-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: yuwen
    spec:
      containers:
        - name: nginx-1
          image: nonono
          ports:
            - containerPort: 80
        - name: nginx-2
          image: nginx:1.14.2
          ports:
            - containerPort: 80
