apiVersion: apps/
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  volumeClaimTemplates:
    - metadata:
        name: www
        labels:
          key: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: xxx
        labels:
          key: xxx
        spec:
          accessModes: ["ReadWrite"]
          storageClassName: "my-storage-class"
          resources:
            requests:
              storage: 1Gi