apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  annotations:
    last-applied: '{"spec":{"replicas":3}}'
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.1
          ports:
            - containerPort: 80
