apiVersion: fn.kpt.dev/v1alpha1
kind: EnsureNameSubstring
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/local-config: 'true'
substring: prod-
editMode: prepend
fieldSpecs:
  - group: dev.example.com
    version: v1
    kind: MyResource
    path: spec/name
