apiVersion: kpt.dev/v1
kind: FunctionResultList
metadata:
  name: fnresults
exitCode: 0
items:
  - image: gcr.io/kpt-fn/set-image:unstable
    exitCode: 0
    results:
      - message: set image from nginx:1.20.2 to bitnami/nginx:1.21.4
        severity: info
        resourceRef:
          apiVersion: v1
          kind: Pod
          name: app1
        field:
          path: spec.containers.image
          currentValue: nginx:1.20.2
          proposedValue: bitnami/nginx:1.21.4
        file:
          path: resources.yaml
      - message: set image from nginx:1.20.2 to bitnami/nginx:1.21.4
        severity: info
        resourceRef:
          apiVersion: v1
          kind: Pod
          name: app2
        field:
          path: spec.containers.image
          currentValue: nginx:1.20.2
          proposedValue: bitnami/nginx:1.21.4
        file:
          path: resources.yaml
          index: 1
