apiVersion: v1
kind: Service
metadata:
  name: myService
  namespace: mySpace
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/upsert-resource:unstable
spec:
  selector:
    app: bar
