#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ -z "${GIT_REF}" ]; then
  echo "GIT_REF must be set"
  exit 1
fi

if [[ ! "${GIT_REF}" =~ ^refs/heads/.* ]]; then
  echo "GIT_REF=${GIT_REF} is not of the expected format refs/heads/*"
  exit 1
fi

BRANCH=${GIT_REF/refs\/heads\//}
echo "BRANCH is ${BRANCH}"

REF=$(git rev-parse --short HEAD)
echo "REF is ${REF}"

IMAGE_REPO=$(echo $IMAGE_REPO | tr '[:upper:]' '[:lower:]')
echo "IMAGE_REPO is ${IMAGE_REPO}"

# We push two tags, <branchname>-latest and <branchname>-git-$GITSHA
# The idea is that if you want the latest version from that branch,
# you'll use the first form, if you want a particular version
# you can use the second form.
#
# We also map main-latest to just "latest" (another reason for people to rename master -> main)
BRANCH_IMAGE_TAG="${BRANCH}-latest"
if [[ "${BRANCH_IMAGE_TAG}" == "main-latest" ]]; then
  BRANCH_IMAGE_TAG="latest"
fi
REF_IMAGE_TAG="${BRANCH}-git-${REF}"
export IMAGE_TAG="${REF_IMAGE_TAG},${BRANCH_IMAGE_TAG}"
echo "IMAGE_TAG is ${IMAGE_TAG}"

# We identify functions that follow this new approach by the presence of the krm-fn-metadata.yaml file.
find . -type f -name "krm-fn-metadata.yaml" -print0 | while IFS= read -r -d '' f; do
  dir=$(dirname "${f}")
  echo "directory: ${dir}"
  pushd "${dir}"
    make push
  popd
done
