#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ -z "${GIT_REF}" ]; then
  echo "GIT_REF must be set"
  exit 1
fi

if [[ ! "${GIT_REF}" =~ ^refs/tags/.* ]]; then
  echo "GIT_REF=${GIT_REF} is not of the expected format refs/tags/*"
  exit 1
fi

TAG=${GIT_REF/refs\/tags\//}
echo "TAG is ${TAG}"

VERSION=${TAG##*/}
PREFIX=${TAG%/*}
echo "PREFIX is ${PREFIX}, VERSION is ${VERSION}"

if [[ ! -d "${PREFIX}" ]]; then
  echo "Directory ${PREFIX} is not found"
  exit 1
fi

export IMAGE_TAG=${VERSION}
cd "${PREFIX}"
make push