apiVersion: fn.kpt.dev/v1alpha1
kind: SetLabels
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  color: orange
  fruit: apple
additionalLabelFields:
  - kind: MyResource
    create: true
    group: dev.example.com
    path: spec/selector/labels
    version: v1
