# call `kpt fn run` on a directory containing this file, mounting the helm chart at /source
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/helm-template
data:
  chart: /source
