apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
  namespace: the-namespace
  annotations:
    annotation-to-delete: "some_value"
data:
  some-key: some-value
---
apiVersion: v1
kind: Namespace
metadata:
  name: the-namespace
