apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrict-clusteradmin-rolebindings
  annotations:
    description: "Restricts use of the cluster-admin role."
    bundles.validator.forsetisecurity.org/cis-k8s-v1.5.1: 5.1.1
    annotation.to.delete: "some_value"
spec:
  enforcementAction: deny
  parameters:
    restrictedRole:
      apiGroup: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
      name: "cluster-admin"
    allowedSubjects:
    - apiGroup: "rbac.authorization.k8s.io"
      kind: "Group"
      name: "system:masters"
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sProhibitRoleWildcardAccess
metadata:
  name: prohibit-role-wildcard-access
  annotations:
    description: "Restricts use of wildcards in Roles and ClusterRoles."
    bundles.validator.forsetisecurity.org/cis-k8s-v1.5.1: 5.1.3
spec:
  enforcementAction: deny
