apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
data:
  some-key: some-value
---
apiVersion: v1
kind: Service
metadata:
  name: the-service
  namespace: example
spec:
  ports:
    - name: etcd-server-ssl
      port: 2380
    - name: etcd-client-ssl
      port: 2379
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: the-service
  namespace: not-match-example
spec:
  ports:
    - name: etcd-server-ssl
      port: 2380
    - name: etcd-client-ssl
      port: 2379
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: example
