apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: shipping-dev
rules:
- resources:
  - jobs
  apiGroups:
  - batch/v1
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creators
  namespace: shipping-dev
roleRef:
  name: job-creator
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: sam@foo-corp.com
  kind: User
  apiGroup: rbac.authorization.k8s.io
