# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CheckSite
on:
  pull_request:
    paths:
      - "functions/**"
      - "examples/**"
      - "site/**"
      - "scripts/generate_catalog/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge gob branch
        run: git worktree add ./gob gob && cp -r gob/* .
      - uses: actions/checkout@v2
        with:
          repository: etefera/href-checker
          ref: docsify
          path: href-checker
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Lint site content
        run: npm i && npm run lint-check
        working-directory: site
      - name: Install Site Checker
        run: yarn install
        working-directory: href-checker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Site Checker
        run: make site-check
