apiVersion: fn.kpt.dev/v1alpha1
kind: SetAnnotationConfig
metadata:
  name: my-func-config
  annotations:
    config.kubernetes.io/local-config: "true"
annotations:
  color: orange
  fruit: apple
fieldSpecs:
  - kind: MyResource
    create: true
    group: dev.example.com
    path: spec/selector/annotations
    version: v1
