apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-namespace-to-prod
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-fn/starlark:unstable
source: |
  # set the namespace on each resource
  def run(r, ns_value):
    for resource in r:
      # mutate the resource
      resource["metadata"]["namespace"] = ns_value
  run(ctx.resource_list["items"], "prod")
